FINAL_TASK_STATUSES = ("SUCCESS", "FAILED", "CANCELLED")
UNAVAILABLE_ROBOT_STATUSES = ("EMERGENCY_STOP", "ERROR", "OFFLINE")

TASK_ROBOT_TYPE = {
    "MOVE_TO_PRODUCT": "PICKY",
    "MOVE_TO_PICKUP": "PICKY",
    "MOVE_TO_STOCK": "PICKY",
    "MOVE_TO_STORAGE": "PICKY",
    "RETURN_HOME": "PICKY",
    "DOCK_IN": "PICKY",
    "CHARGE": "PICKY",
    "SORTING_AND_LOAD": "COBOT",
    "INSPECTION": "COBOT",
    "UNLOAD": "COBOT",
    "STOCKING_PICK": "COBOT",
    "STOCKING_PLACE": "COBOT",
}
