fleet_manager:
  ros__parameters:
    robot_ids:
      - PICKY1
      - PICKY2
      - COBOT1
      - COBOT2
    api_enabled: true
    api_host: "0.0.0.0"
    api_port: 8100
    api_push_interval_sec: 1.0
    waiting_work_poll_period_sec: 5.0
    robot_state_flush_period_sec: 1.0
