MIN_AMR_BATTERY_LEVEL = 20
ROBOT_RESERVED_TASK_STATUSES = ("QUEUED", "ASSIGNED", "RUNNING", "PAUSED")
FINAL_TASK_STATUSES = ("SUCCESS", "FAILED", "CANCELLED")
UNAVAILABLE_ROBOT_STATUSES = ("EMERGENCY_STOP", "ERROR", "OFFLINE")
